export default {
  variablePrefix: "$",
  empty: "",
  separator: ",",
  openParen: "(",
  closeParen: ")",
  space: " ",
  if: "if",
  atIf: "@if",
  atElse: "@else",
  openBrace: "{",
  closeBrace: "}",
  return: "@return",
  module: "@use",
  semicolon: ";",
  singleQuote: "'",
  colon: ":",
  default: "!default",
  function: "@function",
};
